version: '3.9'

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000"
    depends_on:
      - mongo
    volumes:
      - ./go:/opt/go:cached
    networks:
        - "app.network"
    env_file:
      - .env
    deploy:
      replicas: 5

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    ports:
      - "80:80"
    networks:
        - "app.network"



  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ~/apps/mongo:/data/db
    networks:
      - "app.network"

  mongo_express:
    image: mongo-express
    container_name: mongo_express
    depends_on:
      - mongo
    ports:
      - "8081:8081"
    restart: always

networks:
    app.network:



